# Generated by Django 4.2 on 2023-06-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_transaction_created_at_transaction_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='price',
        ),
    ]
