# Generated by Django 4.2 on 2023-06-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_remove_transaction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=10000),
        ),
    ]
