# Generated by Django 4.2 on 2023-06-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currentValue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
