# Generated by Django 4.2.13 on 2024-05-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_transaction_currentvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
