# Generated by Django 4.2.13 on 2024-05-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_transaction_emailverified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='emailVerified',
        ),
        migrations.AddField(
            model_name='user',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
